baseURL = 'https://thelazynfter.blog/'
languageCode = 'en'
title = 'Thelazynfter'
description = "A new generation of AI are making it possible for artists to create amazing works of art through text and natural language."
theme = 'blogging-authority'
copyright = "{year} - thelazynfter.blog"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
disableHugoGeneratorInject = true

[markup.goldmark.renderer]
    unsafe= true
[sitemap]
    changefreq = 'weekly'
    filename = 'sitemap.xml'
    priority = 0.8

menu = ['main', 'footer']

[params]
    'author' = 'Thelazynfter'
    'logo' = 'img/thelazynfter_logo.svg'





[menu]
    [[menu.main]]
      identifier = 'learn'
      name = 'Learn'
      url = '/learn/'
      weight = 1
    [[menu.main]]
      identifier = 'software'
      name = 'NFT Software'
      url = '/learn/software-to-create-nft-art/'
      weight = 2

    [[menu.footer]]
      identifier = 'privacy'
      name = 'Privacy'
      url = '/privacy-policy/'
      weight = 1
    [[menu.footer]]
      identifier = 'disclaimer'
      name = 'Disclaimer'
      url = '/disclaimer/'
      weight = 2
    [[menu.footer]]
      identifier = 'contact'
      name = 'Contact'
      url = '/contact/'
      weight = 3




[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = true
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        enableDNT = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
