baseURL = 'https://thelazynfter.blog/'
languageCode = 'en'
title = 'Thelazynfter'
description = "Simple Cryptocurrency guides about Bitcoin, Solana, Ethereum and Polygon. I also DApp a bit in NFT with Machine Learning."
theme = 'blogging-authority'
copyright = "{year} - thelazynfter.blog"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
disableHugoGeneratorInject = true

[markup.goldmark.renderer]
    unsafe= true
[sitemap]
    changefreq = 'weekly'
    filename = 'sitemap.xml'
    priority = 0.8

menu = ['main', 'footer']

[params]
    'author' = 'Thelazynfter'
    'logo' = 'img/thelazynfter_logo.svg'

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = true
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        enableDNT = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
