baseURL = 'https://thelazynfter.blog/'
languageCode = 'en'
title = 'TheLazyNFTer'
description = 'Learn to generate unique art from text with AI. In this guide you will learn how to use a free machine learning tool to create cryptographic art without writing a single line of code.'
theme = 'blogging-authority'
copyright = "{year} - thelazynfter.blog"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true

[markup.goldmark.renderer]
    unsafe= true
[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

menu = ['main', 'footer']

[params]
    'author' = 'TheLazyNFTer'
    'logo' = 'img/thelazynfter_logo.svg'

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = true
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        enableDNT = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
