baseURL = "https://thelazynfter.blog/"
languageCode = "en"
title = "Thelazynfter"
description = "Explore decentralized gaming guides, tips and tricks. All created and researched by your talkative neighborhood blockchain and NFT blog."
theme = "cryptotheme"

disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
[markup.goldmark.renderer]
unsafe = true

[params]
    favicon = "/img/favicon.ico"
    logo = "/img/thelazynfter_logo.webp"
    author = "Thelazynfter"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.8
