baseURL = 'https://thelazynfter.blog/'
languageCode = 'en-US'
title = 'TheLazyNFTer'
description = "Generate unique art for free with AI art generator. This neural network art generator let's you create nifties art from just your text input."
theme = 'blogging-authority'
copyright = "{year} - thelazynfter.blog"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true

[markup.goldmark.renderer]
    unsafe= true
[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.8

menu = ['main', 'footer']

[params]
    'author' = 'TheLazyNFTer'
    'logo' = 'img/thelazynfter_logo.svg'

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = true
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        enableDNT = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
